"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
import AppShell from "../../components/AppShell";
import {useWorkspace} from "../../lib/useWorkspace";
const types=["Missing Person","Skip Trace","Insurance Fraud","Corporate Investigation","Criminal Defense Support","Civil Litigation","Genealogy / Heir Trace","Forensics","Background Investigation","Other"];
export default function NewCase(){
 const router=useRouter();const {supabase,user,organization}=useWorkspace();const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);const [f,setF]=useState({title:"",type:"Missing Person",priority:"medium",client:"",jurisdiction:"Vietnam",objective:"",legal:"Client-authorized private investigation"});
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!user||!organization)return;setBusy(true);setError(null);const {data,error}=await supabase.from("cases").insert({organization_id:organization.id,title:f.title,case_type:f.type,priority:f.priority,status:"active",jurisdictions:[f.jurisdiction],legal_basis:f.legal,client_reference:f.client||null,lead_investigator:user.id,created_by:user.id,objective:f.objective||null}).select("id").single();if(error||!data){setError(error?.message||"Could not create case");setBusy(false);return;}await supabase.from("case_members").insert({case_id:data.id,organization_id:organization.id,user_id:user.id,case_role:"lead",can_view_restricted:true});router.replace("/cases");};
 return <AppShell title="Open New Case" subtitle="Create a real case record with lawful-purpose controls."><section className="panel">{error&&<div className="alert error">{error}</div>}<form className="form" onSubmit={submit}><label>Case title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Case type<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Client / requesting party<input value={f.client} onChange={e=>setF({...f,client:e.target.value})}/></label><label>Jurisdiction<input required value={f.jurisdiction} onChange={e=>setF({...f,jurisdiction:e.target.value})}/></label><label>Lawful purpose<select value={f.legal} onChange={e=>setF({...f,legal:e.target.value})}><option>Client-authorized private investigation</option><option>Attorney-directed investigation</option><option>Insurance claim investigation</option><option>Corporate internal investigation</option><option>Missing-person search</option><option>Other documented lawful purpose</option></select></label><label className="full">Objective<textarea rows={5} value={f.objective} onChange={e=>setF({...f,objective:e.target.value})}/></label><div className="full"><button className="btn" disabled={busy}>{busy?"Opening…":"Open case"}</button></div></form></section></AppShell>;
}
